! A.C. METHOD OF CHORIN (1965) FOR SOLUTION TO INCOMPRESSIBLE
! CHANNEL FLOW

! WRITTEN BY MR A. J. BRIERLEY

! CRANFIELD UNIVERSITY
! CENTRE FOR COMPUTATIONAL ENGINEERING SCIENCES (CES)
! BEDFORDSHIRE, MK43 OAL, UK

! 24.02.2025

PROGRAM AC

IMPLICIT NONE

REAL :: UA  ! INLET VELOCITY [m/s]
REAL :: DX  ! X GRID SPACING [m]
REAL :: DY  ! Y GRID SPACING [m]
REAL :: L   ! CHANNEL LENGTH [m]
REAL :: W   ! CHANNEL WIDTH [m]
REAL :: H   ! CHANNEL HEIGHT [m]
REAL :: MU  ! DYNAMIC VISCOSITY [Pa*s]
REAL :: NU  ! KINEMATIC VISCOSITY [
REAL :: RHO ! DENSITY [kg/m^3]

INTEGER :: N   ! NUMBER OF ITERATIONS
INTEGER :: RE  ! REYNOLDS NUMBER











END PROGRAM AC
