! FORTRAN PRACTICE PROGRAM

! WRITTEN BY MR A. J. BRIERLEY
! CRANFIELD UNIVERSITY
! CENTRE FOR COMPUTATIONAL ENGINEERING SCIENCES
! BEDFORDSHIRE, MK43 OAL, UK

! 24/02/2025

PROGRAM INIT
IMPLICIT NONE
REAL :: time = 10.0
WRITE(*,*) 'Time = ', tmie
END PROGRAM INIT
 
